version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/fastapi-server"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "dependencies"
      - "javascript"
